#3-8 Seeing the World
locations = ["Canada", "Italy", "Germany", "UK", "Luxemborg"]
print(locations)
print(sorted(locations))
print(locations)
print(sorted(locations, reverse=True))
print(locations)
locations.reverse()
print(locations)
locations.reverse()
print(locations)
locations.sort()
print(locations)
locations.reverse()
print(locations)
